# Generated by Django 4.0.3 on 2022-04-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_username_author_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordsList', models.TextField()),
            ],
        ),
    ]
