# Generated by Django 4.0.3 on 2022-04-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_ssubscriber_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ssubscriber',
            unique_together=set(),
        ),
    ]
